AllCops:
  Include:
    - 'Rakefile'
    - 'lib/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
  Exclude:
    - 'Gemfile.lock'
    - 'Gemfile'
    - 'gemfiles/**/*'
    - '**/*.json'
    - '**/*.yml'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 12

Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/IfUnlessModifier:
  Enabled: false
